default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres                 # Your local PostgreSQL username
  password: password                 # Your local PostgreSQL password
  host: localhost                    # For local Windows PostgreSQL
  port: 5432                         # Default PostgreSQL port
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: suppli_ai_development

test:
  <<: *default
  database: suppli_ai_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>    # Use Render's provided DATABASE_URL
