default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres                 # Local PostgreSQL username
  password: password                 # Local PostgreSQL password
  host: localhost                    # Local PostgreSQL host
  port: 5432                         # Default PostgreSQL port
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: suppli_ai_development

test:
  <<: *default
  database: suppli_ai_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

  cable:
    adapter: postgresql
    url: <%= ENV['DATABASE_URL'] %>
